"""
Saving Tip Pydantic schemas for API request validation and response serialization.
"""

from datetime import datetime
from typing import Optional, List, Literal
from pydantic import BaseModel, Field
from app.database.models import (
    TipType,
    TipStatus,
    PriorityLevel,
    EffortLevel,
    AnalysisSessionStatus,
    ApplianceAnalysisStatus,
    SavingTipInDB,
)


class AISavingTipItem(BaseModel):
    """Structured output item generated by Gemini for a saving tip recommendation"""

    title: str = Field(..., description="Actionable title of the recommendation")
    description: str = Field(
        ...,
        description="Detailed recommendation prose incorporating target appliance metrics",
    )
    tip_type: TipType = Field(..., description="Tip category: CALCULATED or REFERENCE")
    effort_level: EffortLevel = Field(
        ..., description="Effort required: LOW, MEDIUM, HIGH"
    )
    recommended_daily_usage_reduction_hours: Optional[float] = Field(
        default=None,
        description="Recommended daily reduction in hours for CALCULATED tips",
    )
    requires_source: bool = Field(
        default=False,
        description="True if recommendation benefits from external authoritative "
        "web search verification",
    )
    source_query: Optional[str] = Field(
        default=None,
        description="Target search query for retrieving authoritative external documentation",
    )


class ApplianceEvaluationItem(BaseModel):
    """Gemini evaluation item for a specific appliance"""

    appliance_id: str = Field(..., description="Target appliance UUID string")
    analysis_status: ApplianceAnalysisStatus = Field(
        ..., description="Evaluation outcome: EFFICIENT or HAS_RECOMMENDATIONS"
    )
    tips: List[AISavingTipItem] = Field(
        default_factory=list,
        description="List of generated saving tips if HAS_RECOMMENDATIONS",
    )


class HouseholdEvaluationResult(BaseModel):
    """Gemini structured evaluation result for the entire household"""

    evaluations: List[ApplianceEvaluationItem] = Field(
        default_factory=list, description="Per-appliance household evaluation items"
    )


class GenerateTipsResponse(BaseModel):
    """Response returned upon triggering household saving tips generation"""

    session_id: str = Field(..., description="UUID of the initiated analysis session")
    message: str = Field(..., description="Status summary message")
    status: AnalysisSessionStatus = Field(
        ..., description="Session status (e.g. IN_PROGRESS)"
    )


class HouseholdAnalysisStatusResponse(BaseModel):
    """API response model for household analysis status and cooldown metadata"""

    session_status: Optional[AnalysisSessionStatus] = Field(
        default=None, description="Status of current or latest analysis session"
    )
    is_cooldown_active: bool = Field(
        ..., description="Whether 24-hour cooldown is currently active"
    )
    is_household_outdated: bool = Field(
        ..., description="Whether household configuration changed since last analysis"
    )
    current_household_snapshot_version: str = Field(
        ..., description="Snapshot version string of current active appliances"
    )
    analyzed_household_snapshot_version: Optional[str] = Field(
        default=None, description="Snapshot version string of last completed analysis"
    )
    next_allowed_analysis_at: Optional[datetime] = Field(
        default=None, description="UTC timestamp when next analysis is allowed"
    )
    active_appliance_count: int = Field(
        ..., description="Number of active household appliances"
    )


class SavingTipResponse(SavingTipInDB):
    """API response model representing a single saving tip"""

    pass


class SavingTipStatusUpdate(BaseModel):
    """Request model for updating saving tip lifecycle status"""

    status: Literal["active", "completed", "deleted"] = Field(
        ..., description="New status value"
    )


class SavingTipsSummaryResponse(BaseModel):
    """API response model for Saving Tips top summary metrics"""

    total_potential_monthly_savings: float = Field(
        ..., description="Sum of active calculated monthly savings in PHP"
    )
    total_yearly_savings: float = Field(
        ..., description="Projected annual savings in PHP (12x monthly)"
    )
    total_tips_count: int = Field(
        ..., description="Total visible tips count (active + completed + stale)"
    )
    easy_wins_count: int = Field(
        ..., description="Count of visible tips with LOW effort level"
    )
    percentage_bill_reduction: float = Field(
        ...,
        description="Percentage reduction relative to total monthly electricity cost",
    )
