"""
Saving Tip Constants for WattTipid.
"""

MINIMUM_APPLIANCES_FOR_TIPS = 5
MINIMUM_MONTHLY_KWH_FOR_TIPS = 15.0

HIGH_SAVINGS_THRESHOLD_PHP = 250.0
MEDIUM_SAVINGS_THRESHOLD_PHP = 100.0

HIGH_MONTHLY_KWH_THRESHOLD = 100.0
MEDIUM_MONTHLY_KWH_THRESHOLD = 30.0
