# Defines the events block required by nginx.
# Controls connection processing.
events {}


http {

    # Define a server block.
    # A server block handles incoming HTTP requests.
    server {


        # Listen for HTTP traffic on port 80.
        # In production this will usually become 443 with SSL.
        listen 80;


        # Handle all incoming requests.
        location / {


            # Forward the request to the FastAPI service.
            #
            # "watt_tipid_api" is the Docker Compose service name.
            # Docker automatically creates DNS records for services.
            #
            # Nginx receives:
            #   localhost/api
            #
            # Then forwards to:
            #   watt_tipid_api:8000
            #
            proxy_pass http://watt_tipid_api:8000;


            # Preserve the original hostname.
            # Useful for logging and application logic.
            proxy_set_header Host $host;


            # Pass the real client IP address.
            # Without this FastAPI sees nginx's IP.
            proxy_set_header X-Real-IP $remote_addr;


            # Preserve the full chain of client IPs.
            #
            # Example:
            # User -> Nginx -> FastAPI
            #
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


            # Tell FastAPI whether the original request was HTTP or HTTPS.
            #
            # Important when you add SSL later.
            #
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
